# Epilogue: _In the midst of two realities_ {#chapter8}

\chaptermark{In the midst of two realities}

\vspace*{\fill}

---

\small
\noindent 
_This chapter has been published as_: Rojas-Saunero L.P. In the midst of two realities. _Epidemiology_. 2020; 2021;32(1):148-149.
\newpage
\normalsize

To me, the global circumstances of 2020 rebuilt my perception of what being an epidemiologist means. It required me to understand my privileges and, as a result, decipher how to make myself accountable for them.

Seven years ago, I could not even dream of where I am today.  When I finished medical school in my hometown of La Paz, Bolivia (a low-middle income country in South America), I decided to emigrate to Argentina to seek further training in scientific research. There, I was able to deepen my experience and knowledge of epidemiology, up to the point that I felt that to address research questions that required complex data, I required further training in advanced epidemiologic methods. Today, I am a PhD candidate in Epidemiology, and I feel privileged to be at a prestigious university, where I focus on the subfield of causal inference methods development. I have a stable income as a researcher during the pandemic and access to countless resources to grow professionally.

Being part of an international community of epidemiologists (such as the Society of Epidemiologic Research) helped me put in perspective that epidemiology is an umbrella term that covers several specialized subfields and career pathways. And while my dissertation is specifically in a subfield, the pandemic has highlighted that being able to work on a specific subfield is a privilege limited to countries where both public health capacity and up-to-par educational and research resources allow it. In countries like mine, epidemiologists and public health professionals do the fieldwork, build their own data collection infrastructure, analyze the data to answer all kinds of research questions, and interact with governmental authorities and local stakeholders themselves. Working now with colleagues from Bolivia, who are in the pandemic frontline performing all the key aforementioned epidemiologic duties, reminded me that as an epidemiologist, different contexts require me to contribute with a lot more than my specialized skills. 

Being involved in projects happening in Bolivia make me aware of how much of the top research published in highly recognized journals cannot be generalized to minoritized populations, and how much is lost when social determinants are not explored. To put Bolivia in context, it has the second lowest score in Healthcare Access and Quality Index in Latin America and the Caribbean[@fullman2018]. Currently, it has around 0.4 ICU beds per 100000 people[@almeida2021] while high-income countries have a capacity above 25 or more ICU beds per 100000[@halpern2020]. The Bolivian political and economic context[@trigo2020] constrain health care professionals from implementing strategies proposed in prevention, diagnosis, and treatment, during (and beyond) the COVID19 pandemic. For this reason, people have needed to find their own strategies to mitigate the health effects of the pandemic and especially, to help solve the consequences of social inequities. These interventions (which are often labeled as activism) are having a powerful public health impact. 

I am currently part of a multidisciplinary team that founded the Red Estratégica para el Autocuidado Socio-Comunitario (Strategic Network for Socio-Communitary Self-Care)[@reas2020]. We systematize collective experiences and community-based self-management strategies developed in hot spots of political conflict[@bjork-james2020] and marginalized rural areas with the intention of making them visible.  We have interviewed local leaders who are developing strategies that range from opening soup-kitchens to preventing starvation, to initiatives that promote and research traditional medicine as a response to the lack of access to medications for COVID19 symptoms. This experience has helped me understand that strategies born from real need benefit increase global health knowledge and epidemiologic research. Furthermore, although similar realities are being experienced in other countries of the world, they are not yet central to academic research in epidemiology. Thus, I have now understood that if my methodologic research is to have an impact in improving health, then I need to go back to listen and observe health problems from those who are in the frontline and translate this complexity on how we phrase research questions. By focusing on the research questions first, I am sure that we, as epidemiologists of all kinds, will face both the need to collect data that is being neglected, and we will have to improve methodologic research in ways that it can be well disposed to real applications and different contexts.

Being an epidemiologist in 2020 has allowed me to reconnect with my roots and with the motivations that led me to where I am today. It has meant appraising the value of social epidemiology and how to put methods development at people's needs and service. It has meant being critical about the regional frontiers that divide science and epidemiology between the global north and the global south. Finally, I realized that, no matter how far I am from my home country, if I am not accountable for my privilege to this learning process, I will be perpetuating this division.  


\newpage

\printbibliography[segment=\therefsegment,heading=subbibliography]