# 5. Systematic review ----------------------------------------------------


## 5.1 Table 1 --------------------------------------------------------------------

table5.1 <- tibble::tribble(
  ~ Characteristics,
  ~ `N.(%)`,
  "Exposure type",
  NA,
  "Time-fixed or time-varying measured at one time point",
  "45 (79%)",
  "Time-varying",
  "3 (5%)",
  "Time-varying treated as time-fixed",
  "9 (16%)",
  "Target causal parameter",
  NA,
  "Risk difference without elimination of death",
  "1 (2%)",
  "Unclear or not stated",
  "56 (98%)",
  "Median length of follow-up",
  NA,
  "1 to 3 years",
  "0",
  "3 to 5 years",
  "9 (16%)",
  "5 to 10 years",
  "20 (35%)",
  "10 to 15 years",
  "9 (16%)",
  "15 to 20 years",
  "5 (6%)",
  "Above 20 years",
  "14 (25%)",
  "Includes number or percentage of deaths",
  "32 (56%)",
  "Includes number or percentage of loss to follow-up",
  "32 (56%)",
  "Includes number or percentage of mortality by exposure level",
  "10 (18%)",
  "Information on how the competing event of death is handled in the analysis plan",
  NA,
  "Does not include any description of how the event of death was defined",
  "27 (47%)",
  "Only defined death as a censoring event",
  "8 (14%)",
  "Defines the event of death as part of a sensitivity analysis",
  "15 (26%)",
  "Defines the event of death as part of the main analysis with clear description of the methods/assumptions for valid estimation",
  "6 (11%)",
  "Unclear description",
  "1 (2%)",
  "Primary statistical method",
  NA,
  "Cox-proportional hazard model",
  "51 (89%)",
  "Cumulative incidence function",
  "1 (2%)",
  "Fine-Gray sub distribution hazard model",
  "2 (4%)",
  "Multistate model",
  "1 (2%)",
  "Poisson model",
  "1 (2%)",
  "Other",
  "1 (2%)",
  "Primary statistical measure",
  NA,
  "Hazard Ratios",
  "53 (93%)",
  "Risk Ratios",
  "2 (4%)",
  "Cumulative risks (absolute risk - risk difference)",
  "1 (1%)",
  "Sub-distribution hazard ratios",
  "1 (1%)",
  "Interpretation of the primary estimate given the competing event of death",
  NA,
  "No interpretation given",
  "4 (7%)",
  "Only interprets null hypothesis test",
  "3 (5%)",
  "Potentially incomplete/inaccurate interpretation",
  "49 (86%)",
  "Interpretation is explicitly defined as the target causal parameter",
  "1 (2%)",
  "Mentions mortality in discussion section",
  "18 (32%)"
)

legend5.1 <- "Abbreviation: N, number of articles"

